# Generated by Django 4.2.7 on 2024-09-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('school_slogan', models.CharField(max_length=100)),
                ('school_address', models.CharField(max_length=100)),
                ('school_city', models.CharField(max_length=100)),
                ('school_state', models.CharField(max_length=100)),
                ('school_zip', models.IntegerField()),
                ('school_phone', models.CharField(max_length=100)),
                ('school_email', models.EmailField(max_length=254)),
                ('school_photo_logo', models.ImageField(default='media/no_img.jpg', null=True, upload_to='media/')),
                ('school_users_admin', models.IntegerField()),
                ('school_users_operators', models.IntegerField()),
            ],
        ),
    ]
