# Generated by Django 4.2.7 on 2024-09-25 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('school_slogan', models.CharField(max_length=100)),
                ('school_address', models.CharField(max_length=100)),
                ('school_city', models.CharField(max_length=100)),
                ('school_state', models.CharField(max_length=100)),
                ('school_zip', models.IntegerField()),
                ('school_phone', models.CharField(max_length=100)),
                ('school_email', models.EmailField(max_length=254)),
                ('school_photo_logo', models.ImageField(default='media/no_img.jpg', null=True, upload_to='')),
                ('school_users_admin', models.IntegerField()),
                ('school_users_operators', models.IntegerField()),
                ('school_subsidiaries', models.BooleanField(default=False)),
                ('school_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subsidiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsidiary_name', models.CharField(max_length=100)),
                ('subsidiary_slogan', models.CharField(max_length=100)),
                ('subsidiary_address', models.CharField(max_length=100)),
                ('subsidiary_city', models.CharField(max_length=100)),
                ('subsidiary_state', models.CharField(max_length=100)),
                ('subsidiary_zip', models.IntegerField()),
                ('subsidiary_phone', models.CharField(max_length=100)),
                ('subsidiary_email', models.EmailField(max_length=254)),
                ('subsidiary_photo_logo', models.ImageField(default='media/no_img.jpg', null=True, upload_to='media/')),
                ('School', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='api.school')),
            ],
        ),
    ]
